name: Generate Snake

on:
  schedule:  # Se ejecuta una vez al dÃ­a
    - cron: "0 0 * * *"
  workflow_dispatch:  # Permite ejecutarlo manualmente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Generar animaciÃ³n de la serpiente ğŸ
        uses: Platane/snk@v3
        with:
          github_user_name: AlejandroSegura24  # ğŸ‘ˆ Tu nombre de usuario de GitHub
          outputs: dist/github-contribution-grid-snake.svg

      - name: Subir animaciÃ³n al branch 'output'
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}