name: Update README2

on:
  schedule:
    - cron: "0 */12 * * *"   # Ejecuta cada 12 horas
  workflow_dispatch:

permissions:
  contents: write   # Permiso necesario para actualizar README

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      
      - name: Generate recent activity
        uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}